/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InfoRouteImport } from './routes/info'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OripaIdRouteImport } from './routes/oripa.$id'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiOripasRouteImport } from './routes/api/oripas'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCardsRouteImport } from './routes/api/cards'
import { Route as AdminCreateRouteImport } from './routes/admin.create'
import { Route as ApiVerifyDrawIdRouteImport } from './routes/api/verify.$drawId'
import { Route as ApiOripaIdRouteImport } from './routes/api/oripa.$id'
import { Route as ApiMetadataCardIdRouteImport } from './routes/api/metadata.$cardId'
import { Route as ApiDrawsRecentRouteImport } from './routes/api/draws.recent'
import { Route as ApiDrawOripaIdRouteImport } from './routes/api/draw.$oripaId'
import { Route as ApiCardImageCardIdRouteImport } from './routes/api/card-image.$cardId'
import { Route as ApiAdminSeedRouteImport } from './routes/api/admin.seed'
import { Route as ApiAdminOripasRouteImport } from './routes/api/admin.oripas'
import { Route as ApiAdminCardsRouteImport } from './routes/api/admin.cards'
import { Route as AdminPoolIdRouteImport } from './routes/admin.pool.$id'
import { Route as ApiOripaIdPoolRouteImport } from './routes/api/oripa.$id.pool'
import { Route as ApiDrawsUserAddressRouteImport } from './routes/api/draws.user.$address'
import { Route as ApiDrawsStatusDrawIdRouteImport } from './routes/api/draws.status.$drawId'
import { Route as ApiDrawsDecideDrawIdRouteImport } from './routes/api/draws.decide.$drawId'
import { Route as ApiAdminOripaCreateRouteImport } from './routes/api/admin.oripa.create'
import { Route as ApiAdminAuthLogoutRouteImport } from './routes/api/admin.auth.logout'
import { Route as ApiAdminAuthLoginRouteImport } from './routes/api/admin.auth.login'
import { Route as ApiAdminAuthChallengeRouteImport } from './routes/api/admin.auth.challenge'
import { Route as ApiAdminOripaIdResetRouteImport } from './routes/api/admin.oripa.$id.reset'
import { Route as ApiAdminOripaIdRefillRouteImport } from './routes/api/admin.oripa.$id.refill'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OripaIdRoute = OripaIdRouteImport.update({
  id: '/oripa/$id',
  path: '/oripa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOripasRoute = ApiOripasRouteImport.update({
  id: '/api/oripas',
  path: '/api/oripas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsRoute = ApiCardsRouteImport.update({
  id: '/api/cards',
  path: '/api/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)
const ApiVerifyDrawIdRoute = ApiVerifyDrawIdRouteImport.update({
  id: '/api/verify/$drawId',
  path: '/api/verify/$drawId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOripaIdRoute = ApiOripaIdRouteImport.update({
  id: '/api/oripa/$id',
  path: '/api/oripa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataCardIdRoute = ApiMetadataCardIdRouteImport.update({
  id: '/api/metadata/$cardId',
  path: '/api/metadata/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawsRecentRoute = ApiDrawsRecentRouteImport.update({
  id: '/api/draws/recent',
  path: '/api/draws/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawOripaIdRoute = ApiDrawOripaIdRouteImport.update({
  id: '/api/draw/$oripaId',
  path: '/api/draw/$oripaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardImageCardIdRoute = ApiCardImageCardIdRouteImport.update({
  id: '/api/card-image/$cardId',
  path: '/api/card-image/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedRoute = ApiAdminSeedRouteImport.update({
  id: '/api/admin/seed',
  path: '/api/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOripasRoute = ApiAdminOripasRouteImport.update({
  id: '/api/admin/oripas',
  path: '/api/admin/oripas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCardsRoute = ApiAdminCardsRouteImport.update({
  id: '/api/admin/cards',
  path: '/api/admin/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPoolIdRoute = AdminPoolIdRouteImport.update({
  id: '/pool/$id',
  path: '/pool/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiOripaIdPoolRoute = ApiOripaIdPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => ApiOripaIdRoute,
} as any)
const ApiDrawsUserAddressRoute = ApiDrawsUserAddressRouteImport.update({
  id: '/api/draws/user/$address',
  path: '/api/draws/user/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawsStatusDrawIdRoute = ApiDrawsStatusDrawIdRouteImport.update({
  id: '/api/draws/status/$drawId',
  path: '/api/draws/status/$drawId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawsDecideDrawIdRoute = ApiDrawsDecideDrawIdRouteImport.update({
  id: '/api/draws/decide/$drawId',
  path: '/api/draws/decide/$drawId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOripaCreateRoute = ApiAdminOripaCreateRouteImport.update({
  id: '/api/admin/oripa/create',
  path: '/api/admin/oripa/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLogoutRoute = ApiAdminAuthLogoutRouteImport.update({
  id: '/api/admin/auth/logout',
  path: '/api/admin/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLoginRoute = ApiAdminAuthLoginRouteImport.update({
  id: '/api/admin/auth/login',
  path: '/api/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthChallengeRoute = ApiAdminAuthChallengeRouteImport.update({
  id: '/api/admin/auth/challenge',
  path: '/api/admin/auth/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOripaIdResetRoute = ApiAdminOripaIdResetRouteImport.update({
  id: '/api/admin/oripa/$id/reset',
  path: '/api/admin/oripa/$id/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOripaIdRefillRoute = ApiAdminOripaIdRefillRouteImport.update({
  id: '/api/admin/oripa/$id/refill',
  path: '/api/admin/oripa/$id/refill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/info': typeof InfoRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/create': typeof AdminCreateRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/oripas': typeof ApiOripasRoute
  '/api/stats': typeof ApiStatsRoute
  '/oripa/$id': typeof OripaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pool/$id': typeof AdminPoolIdRoute
  '/api/admin/cards': typeof ApiAdminCardsRoute
  '/api/admin/oripas': typeof ApiAdminOripasRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/card-image/$cardId': typeof ApiCardImageCardIdRoute
  '/api/draw/$oripaId': typeof ApiDrawOripaIdRoute
  '/api/draws/recent': typeof ApiDrawsRecentRoute
  '/api/metadata/$cardId': typeof ApiMetadataCardIdRoute
  '/api/oripa/$id': typeof ApiOripaIdRouteWithChildren
  '/api/verify/$drawId': typeof ApiVerifyDrawIdRoute
  '/api/admin/auth/challenge': typeof ApiAdminAuthChallengeRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/oripa/create': typeof ApiAdminOripaCreateRoute
  '/api/draws/decide/$drawId': typeof ApiDrawsDecideDrawIdRoute
  '/api/draws/status/$drawId': typeof ApiDrawsStatusDrawIdRoute
  '/api/draws/user/$address': typeof ApiDrawsUserAddressRoute
  '/api/oripa/$id/pool': typeof ApiOripaIdPoolRoute
  '/api/admin/oripa/$id/refill': typeof ApiAdminOripaIdRefillRoute
  '/api/admin/oripa/$id/reset': typeof ApiAdminOripaIdResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/create': typeof AdminCreateRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/oripas': typeof ApiOripasRoute
  '/api/stats': typeof ApiStatsRoute
  '/oripa/$id': typeof OripaIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pool/$id': typeof AdminPoolIdRoute
  '/api/admin/cards': typeof ApiAdminCardsRoute
  '/api/admin/oripas': typeof ApiAdminOripasRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/card-image/$cardId': typeof ApiCardImageCardIdRoute
  '/api/draw/$oripaId': typeof ApiDrawOripaIdRoute
  '/api/draws/recent': typeof ApiDrawsRecentRoute
  '/api/metadata/$cardId': typeof ApiMetadataCardIdRoute
  '/api/oripa/$id': typeof ApiOripaIdRouteWithChildren
  '/api/verify/$drawId': typeof ApiVerifyDrawIdRoute
  '/api/admin/auth/challenge': typeof ApiAdminAuthChallengeRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/oripa/create': typeof ApiAdminOripaCreateRoute
  '/api/draws/decide/$drawId': typeof ApiDrawsDecideDrawIdRoute
  '/api/draws/status/$drawId': typeof ApiDrawsStatusDrawIdRoute
  '/api/draws/user/$address': typeof ApiDrawsUserAddressRoute
  '/api/oripa/$id/pool': typeof ApiOripaIdPoolRoute
  '/api/admin/oripa/$id/refill': typeof ApiAdminOripaIdRefillRoute
  '/api/admin/oripa/$id/reset': typeof ApiAdminOripaIdResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/info': typeof InfoRoute
  '/leaderboard': typeof LeaderboardRoute
  '/admin/create': typeof AdminCreateRoute
  '/api/cards': typeof ApiCardsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/oripas': typeof ApiOripasRoute
  '/api/stats': typeof ApiStatsRoute
  '/oripa/$id': typeof OripaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pool/$id': typeof AdminPoolIdRoute
  '/api/admin/cards': typeof ApiAdminCardsRoute
  '/api/admin/oripas': typeof ApiAdminOripasRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/card-image/$cardId': typeof ApiCardImageCardIdRoute
  '/api/draw/$oripaId': typeof ApiDrawOripaIdRoute
  '/api/draws/recent': typeof ApiDrawsRecentRoute
  '/api/metadata/$cardId': typeof ApiMetadataCardIdRoute
  '/api/oripa/$id': typeof ApiOripaIdRouteWithChildren
  '/api/verify/$drawId': typeof ApiVerifyDrawIdRoute
  '/api/admin/auth/challenge': typeof ApiAdminAuthChallengeRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/oripa/create': typeof ApiAdminOripaCreateRoute
  '/api/draws/decide/$drawId': typeof ApiDrawsDecideDrawIdRoute
  '/api/draws/status/$drawId': typeof ApiDrawsStatusDrawIdRoute
  '/api/draws/user/$address': typeof ApiDrawsUserAddressRoute
  '/api/oripa/$id/pool': typeof ApiOripaIdPoolRoute
  '/api/admin/oripa/$id/refill': typeof ApiAdminOripaIdRefillRoute
  '/api/admin/oripa/$id/reset': typeof ApiAdminOripaIdResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/info'
    | '/leaderboard'
    | '/admin/create'
    | '/api/cards'
    | '/api/health'
    | '/api/oripas'
    | '/api/stats'
    | '/oripa/$id'
    | '/admin/'
    | '/admin/pool/$id'
    | '/api/admin/cards'
    | '/api/admin/oripas'
    | '/api/admin/seed'
    | '/api/card-image/$cardId'
    | '/api/draw/$oripaId'
    | '/api/draws/recent'
    | '/api/metadata/$cardId'
    | '/api/oripa/$id'
    | '/api/verify/$drawId'
    | '/api/admin/auth/challenge'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/oripa/create'
    | '/api/draws/decide/$drawId'
    | '/api/draws/status/$drawId'
    | '/api/draws/user/$address'
    | '/api/oripa/$id/pool'
    | '/api/admin/oripa/$id/refill'
    | '/api/admin/oripa/$id/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/info'
    | '/leaderboard'
    | '/admin/create'
    | '/api/cards'
    | '/api/health'
    | '/api/oripas'
    | '/api/stats'
    | '/oripa/$id'
    | '/admin'
    | '/admin/pool/$id'
    | '/api/admin/cards'
    | '/api/admin/oripas'
    | '/api/admin/seed'
    | '/api/card-image/$cardId'
    | '/api/draw/$oripaId'
    | '/api/draws/recent'
    | '/api/metadata/$cardId'
    | '/api/oripa/$id'
    | '/api/verify/$drawId'
    | '/api/admin/auth/challenge'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/oripa/create'
    | '/api/draws/decide/$drawId'
    | '/api/draws/status/$drawId'
    | '/api/draws/user/$address'
    | '/api/oripa/$id/pool'
    | '/api/admin/oripa/$id/refill'
    | '/api/admin/oripa/$id/reset'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/info'
    | '/leaderboard'
    | '/admin/create'
    | '/api/cards'
    | '/api/health'
    | '/api/oripas'
    | '/api/stats'
    | '/oripa/$id'
    | '/admin/'
    | '/admin/pool/$id'
    | '/api/admin/cards'
    | '/api/admin/oripas'
    | '/api/admin/seed'
    | '/api/card-image/$cardId'
    | '/api/draw/$oripaId'
    | '/api/draws/recent'
    | '/api/metadata/$cardId'
    | '/api/oripa/$id'
    | '/api/verify/$drawId'
    | '/api/admin/auth/challenge'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/oripa/create'
    | '/api/draws/decide/$drawId'
    | '/api/draws/status/$drawId'
    | '/api/draws/user/$address'
    | '/api/oripa/$id/pool'
    | '/api/admin/oripa/$id/refill'
    | '/api/admin/oripa/$id/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InfoRoute: typeof InfoRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ApiCardsRoute: typeof ApiCardsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOripasRoute: typeof ApiOripasRoute
  ApiStatsRoute: typeof ApiStatsRoute
  OripaIdRoute: typeof OripaIdRoute
  ApiAdminCardsRoute: typeof ApiAdminCardsRoute
  ApiAdminOripasRoute: typeof ApiAdminOripasRoute
  ApiAdminSeedRoute: typeof ApiAdminSeedRoute
  ApiCardImageCardIdRoute: typeof ApiCardImageCardIdRoute
  ApiDrawOripaIdRoute: typeof ApiDrawOripaIdRoute
  ApiDrawsRecentRoute: typeof ApiDrawsRecentRoute
  ApiMetadataCardIdRoute: typeof ApiMetadataCardIdRoute
  ApiOripaIdRoute: typeof ApiOripaIdRouteWithChildren
  ApiVerifyDrawIdRoute: typeof ApiVerifyDrawIdRoute
  ApiAdminAuthChallengeRoute: typeof ApiAdminAuthChallengeRoute
  ApiAdminAuthLoginRoute: typeof ApiAdminAuthLoginRoute
  ApiAdminAuthLogoutRoute: typeof ApiAdminAuthLogoutRoute
  ApiAdminOripaCreateRoute: typeof ApiAdminOripaCreateRoute
  ApiDrawsDecideDrawIdRoute: typeof ApiDrawsDecideDrawIdRoute
  ApiDrawsStatusDrawIdRoute: typeof ApiDrawsStatusDrawIdRoute
  ApiDrawsUserAddressRoute: typeof ApiDrawsUserAddressRoute
  ApiAdminOripaIdRefillRoute: typeof ApiAdminOripaIdRefillRoute
  ApiAdminOripaIdResetRoute: typeof ApiAdminOripaIdResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/oripa/$id': {
      id: '/oripa/$id'
      path: '/oripa/$id'
      fullPath: '/oripa/$id'
      preLoaderRoute: typeof OripaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oripas': {
      id: '/api/oripas'
      path: '/api/oripas'
      fullPath: '/api/oripas'
      preLoaderRoute: typeof ApiOripasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards': {
      id: '/api/cards'
      path: '/api/cards'
      fullPath: '/api/cards'
      preLoaderRoute: typeof ApiCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/verify/$drawId': {
      id: '/api/verify/$drawId'
      path: '/api/verify/$drawId'
      fullPath: '/api/verify/$drawId'
      preLoaderRoute: typeof ApiVerifyDrawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oripa/$id': {
      id: '/api/oripa/$id'
      path: '/api/oripa/$id'
      fullPath: '/api/oripa/$id'
      preLoaderRoute: typeof ApiOripaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/$cardId': {
      id: '/api/metadata/$cardId'
      path: '/api/metadata/$cardId'
      fullPath: '/api/metadata/$cardId'
      preLoaderRoute: typeof ApiMetadataCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draws/recent': {
      id: '/api/draws/recent'
      path: '/api/draws/recent'
      fullPath: '/api/draws/recent'
      preLoaderRoute: typeof ApiDrawsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draw/$oripaId': {
      id: '/api/draw/$oripaId'
      path: '/api/draw/$oripaId'
      fullPath: '/api/draw/$oripaId'
      preLoaderRoute: typeof ApiDrawOripaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/card-image/$cardId': {
      id: '/api/card-image/$cardId'
      path: '/api/card-image/$cardId'
      fullPath: '/api/card-image/$cardId'
      preLoaderRoute: typeof ApiCardImageCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed': {
      id: '/api/admin/seed'
      path: '/api/admin/seed'
      fullPath: '/api/admin/seed'
      preLoaderRoute: typeof ApiAdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/oripas': {
      id: '/api/admin/oripas'
      path: '/api/admin/oripas'
      fullPath: '/api/admin/oripas'
      preLoaderRoute: typeof ApiAdminOripasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cards': {
      id: '/api/admin/cards'
      path: '/api/admin/cards'
      fullPath: '/api/admin/cards'
      preLoaderRoute: typeof ApiAdminCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pool/$id': {
      id: '/admin/pool/$id'
      path: '/pool/$id'
      fullPath: '/admin/pool/$id'
      preLoaderRoute: typeof AdminPoolIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/oripa/$id/pool': {
      id: '/api/oripa/$id/pool'
      path: '/pool'
      fullPath: '/api/oripa/$id/pool'
      preLoaderRoute: typeof ApiOripaIdPoolRouteImport
      parentRoute: typeof ApiOripaIdRoute
    }
    '/api/draws/user/$address': {
      id: '/api/draws/user/$address'
      path: '/api/draws/user/$address'
      fullPath: '/api/draws/user/$address'
      preLoaderRoute: typeof ApiDrawsUserAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draws/status/$drawId': {
      id: '/api/draws/status/$drawId'
      path: '/api/draws/status/$drawId'
      fullPath: '/api/draws/status/$drawId'
      preLoaderRoute: typeof ApiDrawsStatusDrawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draws/decide/$drawId': {
      id: '/api/draws/decide/$drawId'
      path: '/api/draws/decide/$drawId'
      fullPath: '/api/draws/decide/$drawId'
      preLoaderRoute: typeof ApiDrawsDecideDrawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/oripa/create': {
      id: '/api/admin/oripa/create'
      path: '/api/admin/oripa/create'
      fullPath: '/api/admin/oripa/create'
      preLoaderRoute: typeof ApiAdminOripaCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/logout': {
      id: '/api/admin/auth/logout'
      path: '/api/admin/auth/logout'
      fullPath: '/api/admin/auth/logout'
      preLoaderRoute: typeof ApiAdminAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/login': {
      id: '/api/admin/auth/login'
      path: '/api/admin/auth/login'
      fullPath: '/api/admin/auth/login'
      preLoaderRoute: typeof ApiAdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/challenge': {
      id: '/api/admin/auth/challenge'
      path: '/api/admin/auth/challenge'
      fullPath: '/api/admin/auth/challenge'
      preLoaderRoute: typeof ApiAdminAuthChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/oripa/$id/reset': {
      id: '/api/admin/oripa/$id/reset'
      path: '/api/admin/oripa/$id/reset'
      fullPath: '/api/admin/oripa/$id/reset'
      preLoaderRoute: typeof ApiAdminOripaIdResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/oripa/$id/refill': {
      id: '/api/admin/oripa/$id/refill'
      path: '/api/admin/oripa/$id/refill'
      fullPath: '/api/admin/oripa/$id/refill'
      preLoaderRoute: typeof ApiAdminOripaIdRefillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCreateRoute: typeof AdminCreateRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPoolIdRoute: typeof AdminPoolIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateRoute: AdminCreateRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPoolIdRoute: AdminPoolIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiOripaIdRouteChildren {
  ApiOripaIdPoolRoute: typeof ApiOripaIdPoolRoute
}

const ApiOripaIdRouteChildren: ApiOripaIdRouteChildren = {
  ApiOripaIdPoolRoute: ApiOripaIdPoolRoute,
}

const ApiOripaIdRouteWithChildren = ApiOripaIdRoute._addFileChildren(
  ApiOripaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InfoRoute: InfoRoute,
  LeaderboardRoute: LeaderboardRoute,
  ApiCardsRoute: ApiCardsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOripasRoute: ApiOripasRoute,
  ApiStatsRoute: ApiStatsRoute,
  OripaIdRoute: OripaIdRoute,
  ApiAdminCardsRoute: ApiAdminCardsRoute,
  ApiAdminOripasRoute: ApiAdminOripasRoute,
  ApiAdminSeedRoute: ApiAdminSeedRoute,
  ApiCardImageCardIdRoute: ApiCardImageCardIdRoute,
  ApiDrawOripaIdRoute: ApiDrawOripaIdRoute,
  ApiDrawsRecentRoute: ApiDrawsRecentRoute,
  ApiMetadataCardIdRoute: ApiMetadataCardIdRoute,
  ApiOripaIdRoute: ApiOripaIdRouteWithChildren,
  ApiVerifyDrawIdRoute: ApiVerifyDrawIdRoute,
  ApiAdminAuthChallengeRoute: ApiAdminAuthChallengeRoute,
  ApiAdminAuthLoginRoute: ApiAdminAuthLoginRoute,
  ApiAdminAuthLogoutRoute: ApiAdminAuthLogoutRoute,
  ApiAdminOripaCreateRoute: ApiAdminOripaCreateRoute,
  ApiDrawsDecideDrawIdRoute: ApiDrawsDecideDrawIdRoute,
  ApiDrawsStatusDrawIdRoute: ApiDrawsStatusDrawIdRoute,
  ApiDrawsUserAddressRoute: ApiDrawsUserAddressRoute,
  ApiAdminOripaIdRefillRoute: ApiAdminOripaIdRefillRoute,
  ApiAdminOripaIdResetRoute: ApiAdminOripaIdResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
