/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OripaIdRouteImport } from './routes/oripa.$id'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiOripasRouteImport } from './routes/api/oripas'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOripaIdRouteImport } from './routes/api/oripa.$id'
import { Route as ApiMetadataCardIdRouteImport } from './routes/api/metadata.$cardId'
import { Route as ApiDrawsRecentRouteImport } from './routes/api/draws.recent'
import { Route as ApiDrawOripaIdRouteImport } from './routes/api/draw.$oripaId'
import { Route as ApiCardImageCardIdRouteImport } from './routes/api/card-image.$cardId'
import { Route as ApiAdminSeedRouteImport } from './routes/api/admin.seed'
import { Route as ApiOripaIdPoolRouteImport } from './routes/api/oripa.$id.pool'
import { Route as ApiDrawsUserAddressRouteImport } from './routes/api/draws.user.$address'
import { Route as ApiDrawsStatusDrawIdRouteImport } from './routes/api/draws.status.$drawId'
import { Route as ApiDrawsDecideDrawIdRouteImport } from './routes/api/draws.decide.$drawId'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OripaIdRoute = OripaIdRouteImport.update({
  id: '/oripa/$id',
  path: '/oripa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOripasRoute = ApiOripasRouteImport.update({
  id: '/api/oripas',
  path: '/api/oripas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOripaIdRoute = ApiOripaIdRouteImport.update({
  id: '/api/oripa/$id',
  path: '/api/oripa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetadataCardIdRoute = ApiMetadataCardIdRouteImport.update({
  id: '/api/metadata/$cardId',
  path: '/api/metadata/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawsRecentRoute = ApiDrawsRecentRouteImport.update({
  id: '/api/draws/recent',
  path: '/api/draws/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawOripaIdRoute = ApiDrawOripaIdRouteImport.update({
  id: '/api/draw/$oripaId',
  path: '/api/draw/$oripaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardImageCardIdRoute = ApiCardImageCardIdRouteImport.update({
  id: '/api/card-image/$cardId',
  path: '/api/card-image/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedRoute = ApiAdminSeedRouteImport.update({
  id: '/api/admin/seed',
  path: '/api/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOripaIdPoolRoute = ApiOripaIdPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => ApiOripaIdRoute,
} as any)
const ApiDrawsUserAddressRoute = ApiDrawsUserAddressRouteImport.update({
  id: '/api/draws/user/$address',
  path: '/api/draws/user/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawsStatusDrawIdRoute = ApiDrawsStatusDrawIdRouteImport.update({
  id: '/api/draws/status/$drawId',
  path: '/api/draws/status/$drawId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawsDecideDrawIdRoute = ApiDrawsDecideDrawIdRouteImport.update({
  id: '/api/draws/decide/$drawId',
  path: '/api/draws/decide/$drawId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/oripas': typeof ApiOripasRoute
  '/api/stats': typeof ApiStatsRoute
  '/oripa/$id': typeof OripaIdRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/card-image/$cardId': typeof ApiCardImageCardIdRoute
  '/api/draw/$oripaId': typeof ApiDrawOripaIdRoute
  '/api/draws/recent': typeof ApiDrawsRecentRoute
  '/api/metadata/$cardId': typeof ApiMetadataCardIdRoute
  '/api/oripa/$id': typeof ApiOripaIdRouteWithChildren
  '/api/draws/decide/$drawId': typeof ApiDrawsDecideDrawIdRoute
  '/api/draws/status/$drawId': typeof ApiDrawsStatusDrawIdRoute
  '/api/draws/user/$address': typeof ApiDrawsUserAddressRoute
  '/api/oripa/$id/pool': typeof ApiOripaIdPoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/oripas': typeof ApiOripasRoute
  '/api/stats': typeof ApiStatsRoute
  '/oripa/$id': typeof OripaIdRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/card-image/$cardId': typeof ApiCardImageCardIdRoute
  '/api/draw/$oripaId': typeof ApiDrawOripaIdRoute
  '/api/draws/recent': typeof ApiDrawsRecentRoute
  '/api/metadata/$cardId': typeof ApiMetadataCardIdRoute
  '/api/oripa/$id': typeof ApiOripaIdRouteWithChildren
  '/api/draws/decide/$drawId': typeof ApiDrawsDecideDrawIdRoute
  '/api/draws/status/$drawId': typeof ApiDrawsStatusDrawIdRoute
  '/api/draws/user/$address': typeof ApiDrawsUserAddressRoute
  '/api/oripa/$id/pool': typeof ApiOripaIdPoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/oripas': typeof ApiOripasRoute
  '/api/stats': typeof ApiStatsRoute
  '/oripa/$id': typeof OripaIdRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/card-image/$cardId': typeof ApiCardImageCardIdRoute
  '/api/draw/$oripaId': typeof ApiDrawOripaIdRoute
  '/api/draws/recent': typeof ApiDrawsRecentRoute
  '/api/metadata/$cardId': typeof ApiMetadataCardIdRoute
  '/api/oripa/$id': typeof ApiOripaIdRouteWithChildren
  '/api/draws/decide/$drawId': typeof ApiDrawsDecideDrawIdRoute
  '/api/draws/status/$drawId': typeof ApiDrawsStatusDrawIdRoute
  '/api/draws/user/$address': typeof ApiDrawsUserAddressRoute
  '/api/oripa/$id/pool': typeof ApiOripaIdPoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/leaderboard'
    | '/api/health'
    | '/api/oripas'
    | '/api/stats'
    | '/oripa/$id'
    | '/api/admin/seed'
    | '/api/card-image/$cardId'
    | '/api/draw/$oripaId'
    | '/api/draws/recent'
    | '/api/metadata/$cardId'
    | '/api/oripa/$id'
    | '/api/draws/decide/$drawId'
    | '/api/draws/status/$drawId'
    | '/api/draws/user/$address'
    | '/api/oripa/$id/pool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/leaderboard'
    | '/api/health'
    | '/api/oripas'
    | '/api/stats'
    | '/oripa/$id'
    | '/api/admin/seed'
    | '/api/card-image/$cardId'
    | '/api/draw/$oripaId'
    | '/api/draws/recent'
    | '/api/metadata/$cardId'
    | '/api/oripa/$id'
    | '/api/draws/decide/$drawId'
    | '/api/draws/status/$drawId'
    | '/api/draws/user/$address'
    | '/api/oripa/$id/pool'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/leaderboard'
    | '/api/health'
    | '/api/oripas'
    | '/api/stats'
    | '/oripa/$id'
    | '/api/admin/seed'
    | '/api/card-image/$cardId'
    | '/api/draw/$oripaId'
    | '/api/draws/recent'
    | '/api/metadata/$cardId'
    | '/api/oripa/$id'
    | '/api/draws/decide/$drawId'
    | '/api/draws/status/$drawId'
    | '/api/draws/user/$address'
    | '/api/oripa/$id/pool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOripasRoute: typeof ApiOripasRoute
  ApiStatsRoute: typeof ApiStatsRoute
  OripaIdRoute: typeof OripaIdRoute
  ApiAdminSeedRoute: typeof ApiAdminSeedRoute
  ApiCardImageCardIdRoute: typeof ApiCardImageCardIdRoute
  ApiDrawOripaIdRoute: typeof ApiDrawOripaIdRoute
  ApiDrawsRecentRoute: typeof ApiDrawsRecentRoute
  ApiMetadataCardIdRoute: typeof ApiMetadataCardIdRoute
  ApiOripaIdRoute: typeof ApiOripaIdRouteWithChildren
  ApiDrawsDecideDrawIdRoute: typeof ApiDrawsDecideDrawIdRoute
  ApiDrawsStatusDrawIdRoute: typeof ApiDrawsStatusDrawIdRoute
  ApiDrawsUserAddressRoute: typeof ApiDrawsUserAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oripa/$id': {
      id: '/oripa/$id'
      path: '/oripa/$id'
      fullPath: '/oripa/$id'
      preLoaderRoute: typeof OripaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oripas': {
      id: '/api/oripas'
      path: '/api/oripas'
      fullPath: '/api/oripas'
      preLoaderRoute: typeof ApiOripasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oripa/$id': {
      id: '/api/oripa/$id'
      path: '/api/oripa/$id'
      fullPath: '/api/oripa/$id'
      preLoaderRoute: typeof ApiOripaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metadata/$cardId': {
      id: '/api/metadata/$cardId'
      path: '/api/metadata/$cardId'
      fullPath: '/api/metadata/$cardId'
      preLoaderRoute: typeof ApiMetadataCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draws/recent': {
      id: '/api/draws/recent'
      path: '/api/draws/recent'
      fullPath: '/api/draws/recent'
      preLoaderRoute: typeof ApiDrawsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draw/$oripaId': {
      id: '/api/draw/$oripaId'
      path: '/api/draw/$oripaId'
      fullPath: '/api/draw/$oripaId'
      preLoaderRoute: typeof ApiDrawOripaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/card-image/$cardId': {
      id: '/api/card-image/$cardId'
      path: '/api/card-image/$cardId'
      fullPath: '/api/card-image/$cardId'
      preLoaderRoute: typeof ApiCardImageCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed': {
      id: '/api/admin/seed'
      path: '/api/admin/seed'
      fullPath: '/api/admin/seed'
      preLoaderRoute: typeof ApiAdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oripa/$id/pool': {
      id: '/api/oripa/$id/pool'
      path: '/pool'
      fullPath: '/api/oripa/$id/pool'
      preLoaderRoute: typeof ApiOripaIdPoolRouteImport
      parentRoute: typeof ApiOripaIdRoute
    }
    '/api/draws/user/$address': {
      id: '/api/draws/user/$address'
      path: '/api/draws/user/$address'
      fullPath: '/api/draws/user/$address'
      preLoaderRoute: typeof ApiDrawsUserAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draws/status/$drawId': {
      id: '/api/draws/status/$drawId'
      path: '/api/draws/status/$drawId'
      fullPath: '/api/draws/status/$drawId'
      preLoaderRoute: typeof ApiDrawsStatusDrawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draws/decide/$drawId': {
      id: '/api/draws/decide/$drawId'
      path: '/api/draws/decide/$drawId'
      fullPath: '/api/draws/decide/$drawId'
      preLoaderRoute: typeof ApiDrawsDecideDrawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiOripaIdRouteChildren {
  ApiOripaIdPoolRoute: typeof ApiOripaIdPoolRoute
}

const ApiOripaIdRouteChildren: ApiOripaIdRouteChildren = {
  ApiOripaIdPoolRoute: ApiOripaIdPoolRoute,
}

const ApiOripaIdRouteWithChildren = ApiOripaIdRoute._addFileChildren(
  ApiOripaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  LeaderboardRoute: LeaderboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOripasRoute: ApiOripasRoute,
  ApiStatsRoute: ApiStatsRoute,
  OripaIdRoute: OripaIdRoute,
  ApiAdminSeedRoute: ApiAdminSeedRoute,
  ApiCardImageCardIdRoute: ApiCardImageCardIdRoute,
  ApiDrawOripaIdRoute: ApiDrawOripaIdRoute,
  ApiDrawsRecentRoute: ApiDrawsRecentRoute,
  ApiMetadataCardIdRoute: ApiMetadataCardIdRoute,
  ApiOripaIdRoute: ApiOripaIdRouteWithChildren,
  ApiDrawsDecideDrawIdRoute: ApiDrawsDecideDrawIdRoute,
  ApiDrawsStatusDrawIdRoute: ApiDrawsStatusDrawIdRoute,
  ApiDrawsUserAddressRoute: ApiDrawsUserAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
